defaults
  mode http
  log global
  option httplog
  option  http-server-close
  option  dontlognull
  option  redispatch
  option  contstats
  retries 3
  backlog 10000
  timeout client          25s
  timeout connect          5s
  timeout server          25s
# timeout tunnel available in ALOHA 5.5 or HAProxy 1.5-dev10 and higher
  timeout tunnel        3600s
  timeout http-keep-alive  1s
  timeout http-request    15s
  timeout queue           30s
  timeout tarpit          60s
  default-server inter 3s rise 2 fall 3
  option forwardfor
 
frontend ft_proxy
  bind 0.0.0.0:80 name http
  maxconn 10000
  default_backend bk_nodebb
 
backend bk_nodebb                      
  balance roundrobin
  cookie server.id insert indirect nocache
#  server nodebb1 nodebb1:4567 maxconn 10000 weight 10 cookie nodebb1 check
#  server nodebb2 nodebb2:4567 maxconn 10000 weight 10 cookie nodebb2 check
